name: flutter_ocr_verifik
description: Verifik demo.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ocr_sdk: 1.1.4
  flutter_tesseract_ocr: 0.4.24
  get_it: 7.6.6
  image_picker: 1.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
