name: flutter_ocr_verifik
description: Verifik demo.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  dio: ^5.4.0
  dotted_border: 2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_dropzone: 3.0.6
  freezed: 2.4.6
  freezed_annotation: 2.4.1
  get_it: 7.6.6
  go_router: 13.0.1
  image_picker: 1.0.7
  json_annotation: 4.8.1
  json_serializable: 6.7.1

dev_dependencies:
  build_runner: 2.4.7
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/png/
